# Generated by Django 2.1 on 2020-11-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no-direction', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no-name', max_length=64)),
                ('surname', models.CharField(default='no-surname', max_length=64)),
                ('salary', models.DecimalField(decimal_places=2, default=150000.0, max_digits=9)),
                ('is_staff', models.BooleanField(default=False)),
                ('direct', models.ManyToManyField(blank=True, to='projects.Direction')),
                ('serts', models.ManyToManyField(blank=True, to='projects.Sertificate')),
            ],
        ),
        migrations.CreateModel(
            name='StaffListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no-position', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='sl_position',
            field=models.ManyToManyField(blank=True, to='projects.StaffListPosition'),
        ),
    ]
