# Generated by Django 2.2 on 2020-11-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='staff/profiles'),
        ),
    ]
